# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 395aa926b1a994337530b2837eccf4d9ceb1340cdcea0ddeadebcabe5e629d5f2d1aef177956412888e1a5217d8221479ed077b66b9058838d9cff6f1ddedfb5

test:
  secret_key_base: 97358aa378d4ca7a277175fe828e9a5415353393b9e4fc8ecd229db4e84d8f8caae9d11e7eb1ae6bd2793802abfdb435f0773f3953989d3e4279223c802e2ea6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
